User.create!([
  {email: "rodrigo@masterchef.com", password: "123123", kind: "admin", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2017-04-30 17:45:30", last_sign_in_at: "2017-04-30 17:39:35", current_sign_in_ip: "192.168.0.15", last_sign_in_ip: "192.168.0.15"},
  {email: "parnas@masterchef.com", password: "123123", kind: "admin", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil}
])
Restaurant.create!([
  {name: "Kip & Friet - Kip & Friet", link: "https://www.thuisbezorgd.nl/kip-friet", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 31586, asset_updated_at: "2017-04-30 16:45:43", description: nil},
  {name: "Chicago Spareribs - Easy to eat, hard to forget", link: "https://www.thuisbezorgd.nl/chicago-spareribs-oost", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 13928, asset_updated_at: "2017-04-30 16:45:44", description: nil},
  {name: "SLA - Biologische salades, veggie bowls, soepen & juices.", link: "https://www.thuisbezorgd.nl/sla-middenweg", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 3780, asset_updated_at: "2017-04-30 16:45:45", description: nil},
  {name: "Döner House - Lekker eten & bestellen bij Döner House!", link: "https://www.thuisbezorgd.nl/doner-house", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6263, asset_updated_at: "2017-04-30 16:45:45", description: nil},
  {name: "Fratelli d'Italia - Als beste beoordeelde pizzeria in Amsterdam!!", link: "https://www.thuisbezorgd.nl/fratelli-ditalia", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7406, asset_updated_at: "2017-04-30 16:45:46", description: nil},
  {name: "New York Pizza - The taste of NEW YORK PIZZA", link: "https://www.thuisbezorgd.nl/new-york-pizza-diemen", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4971, asset_updated_at: "2017-04-30 16:45:46", description: nil},
  {name: "Sushi House - Sushi restaurant", link: "https://www.thuisbezorgd.nl/sushi-house", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12758, asset_updated_at: "2017-04-30 16:45:47", description: nil},
  {name: "Sushi Su - Dagelijks verse sushi!", link: "https://www.thuisbezorgd.nl/sushi-su", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 16193, asset_updated_at: "2017-04-30 16:45:47", description: nil},
  {name: "Nieuw Zuid - Lekker en snel!", link: "https://www.thuisbezorgd.nl/nieuw-zuid", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10310, asset_updated_at: "2017-04-30 16:45:48", description: nil},
  {name: "Kong Kha - authentiek Thais!", link: "https://www.thuisbezorgd.nl/kong-kha", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 22361, asset_updated_at: "2017-04-30 16:45:49", description: nil},
  {name: "Wok King Grill - wok en sushi!", link: "https://www.thuisbezorgd.nl/wokking", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9491, asset_updated_at: "2017-04-30 16:45:49", description: nil},
  {name: "Indonesia Indah - Een kwalitatieve en bewuste keuze! 100% Halal!", link: "https://www.thuisbezorgd.nl/indonesia-indah", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6802, asset_updated_at: "2017-04-30 16:45:50", description: nil},
  {name: "Presidente - Pizza, pasta, calzone en salade", link: "https://www.thuisbezorgd.nl/presidente", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 21562, asset_updated_at: "2017-04-30 16:45:50", description: nil},
  {name: "Natraj Indian Restaurant - Indian Tandoori Restaurant", link: "https://www.thuisbezorgd.nl/natraj-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 15606, asset_updated_at: "2017-04-30 16:45:51", description: nil},
  {name: "Warung Atika - Traditioneel Indonesisch eten voor een eerlijke prijs!", link: "https://www.thuisbezorgd.nl/warung-atika", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10449, asset_updated_at: "2017-04-30 16:45:51", description: nil},
  {name: "Taco Mundo - fresh made mex", link: "https://www.thuisbezorgd.nl/taco-mundo-amsterdam-ceintuurbaan", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6414, asset_updated_at: "2017-04-30 16:45:52", description: nil},
  {name: "CIRO 1939 - Pizzeria Straordinaria", link: "https://www.thuisbezorgd.nl/ciro-1939", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6493, asset_updated_at: "2017-04-30 16:45:52", description: nil},
  {name: "Pocadio Express - Lekker en snel!", link: "https://www.thuisbezorgd.nl/pocadio-express", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 13161, asset_updated_at: "2017-04-30 16:45:53", description: nil},
  {name: "Papa John's - Better Ingredients. Better Pizza.", link: "https://www.thuisbezorgd.nl/papa-johns-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 104428, asset_updated_at: "2017-04-30 16:45:54", description: nil},
  {name: "Spies - heerlijk eten", link: "https://www.thuisbezorgd.nl/spies", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 11162, asset_updated_at: "2017-04-30 16:45:55", description: nil},
  {name: "Namaste India - Heerlijk Indiaas eten!", link: "https://www.thuisbezorgd.nl/namaste-india-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6423, asset_updated_at: "2017-04-30 16:45:56", description: nil},
  {name: "Eetcafé Lago - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/eetcafe-lago", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7563, asset_updated_at: "2017-04-30 16:45:56", description: nil},
  {name: "Rosticceria Italiana - Authentiek Italiaans Genieten!", link: "https://www.thuisbezorgd.nl/rosticceria-italiana", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12874, asset_updated_at: "2017-04-30 16:45:57", description: nil},
  {name: "El Shygh - 100% HALAL", link: "https://www.thuisbezorgd.nl/el-shygh", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 14172, asset_updated_at: "2017-04-30 16:45:57", description: nil},
  {name: "India Roti Room - De specialist sinds 1994", link: "https://www.thuisbezorgd.nl/india-roti-room-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5492, asset_updated_at: "2017-04-30 16:45:58", description: nil},
  {name: "Eetcafe Ibis Ethiopisch restaurant - De enige echte Afrikaan aan de Amstel!", link: "https://www.thuisbezorgd.nl/eetcafe-ibis", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8886, asset_updated_at: "2017-04-30 16:45:58", description: nil},
  {name: "Steakhouse Pizzeria van Woustraat - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/steakhouse-pizzria-van-woustraat", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8246, asset_updated_at: "2017-04-30 16:45:59", description: nil},
  {name: "Italiaans restaurant Casa Pino - De echte Italiaanse keuken en pizza's!", link: "https://www.thuisbezorgd.nl/casa-pino", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19185, asset_updated_at: "2017-04-30 16:45:59", description: nil},
  {name: "Royale biladi café en restaurant - Royale Biladi Café & Restaurant", link: "https://www.thuisbezorgd.nl/royale-biladi-cafe-en-restaurant", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 82663, asset_updated_at: "2017-04-30 16:46:00", description: nil},
  {name: "Restaurant Yatta - De lekkerste sushi bij Yatta Sushi!", link: "https://www.thuisbezorgd.nl/sushi-yatta", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5295, asset_updated_at: "2017-04-30 16:46:01", description: nil},
  {name: "Meram Restaurant & cafe - Grote variëteit aan authentiek Turkse gerechten!", link: "https://www.thuisbezorgd.nl/meram-restaurant-cafe", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7843, asset_updated_at: "2017-04-30 16:46:01", description: nil},
  {name: "Wonny's Eethuis - Authentiek Surinaams, niet te versmaden!", link: "https://www.thuisbezorgd.nl/wonnys-eethuis", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5759, asset_updated_at: "2017-04-30 16:46:02", description: nil},
  {name: "Thaicoon - Thai kitchen", link: "https://www.thuisbezorgd.nl/thaicoon-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6725, asset_updated_at: "2017-04-30 16:46:03", description: nil},
  {name: "Taj Tandoori - Creatie van Indian Roti Room", link: "https://www.thuisbezorgd.nl/taj-tandoori", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19323, asset_updated_at: "2017-04-30 16:46:03", description: nil},
  {name: "Sushito - Sushito poké bowls & sushi burritos", link: "https://www.thuisbezorgd.nl/sushito", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 11967, asset_updated_at: "2017-04-30 16:46:04", description: nil},
  {name: "Somjit Thai - Thai cuisine specialties", link: "https://www.thuisbezorgd.nl/somjit", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 17822, asset_updated_at: "2017-04-30 16:46:04", description: nil},
  {name: "La Dolce - Professore di cibo Italiano", link: "https://www.thuisbezorgd.nl/la-dolce", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12350, asset_updated_at: "2017-04-30 16:46:05", description: nil},
  {name: "Lo Sbrano - Pizza's & Antipasti", link: "https://www.thuisbezorgd.nl/lo-sbrano", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 78831, asset_updated_at: "2017-04-30 16:46:05", description: nil},
  {name: "Perry's - Exotisch Surinaams en Indiaas", link: "https://www.thuisbezorgd.nl/perrys", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9269, asset_updated_at: "2017-04-30 16:46:06", description: nil},
  {name: "Peperoncino - Italiaanse Gerechten", link: "https://www.thuisbezorgd.nl/peperoncino", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4186, asset_updated_at: "2017-04-30 16:46:07", description: nil},
  {name: "Fresh2Go Sushi - De lekkerste sushi in Amsterdam!", link: "https://www.thuisbezorgd.nl/fresh2go", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6324, asset_updated_at: "2017-04-30 16:46:07", description: nil},
  {name: "Chiapas - Taco Cartel - Tacos & Burritos", link: "https://www.thuisbezorgd.nl/chiapas-taco-kartel", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10043, asset_updated_at: "2017-04-30 16:46:08", description: nil},
  {name: "CHEFS Poulet & Frites - Female Power Traiteurs", link: "https://www.thuisbezorgd.nl/traiteur-chefs-co", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9819, asset_updated_at: "2017-04-30 16:46:08", description: nil},
  {name: "Everest Kitchen - Nepalese & Indian Food", link: "https://www.thuisbezorgd.nl/everest-kitchen", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7046, asset_updated_at: "2017-04-30 16:46:09", description: nil},
  {name: "San Siro - Pizzeria", link: "https://www.thuisbezorgd.nl/san-siro", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 31250, asset_updated_at: "2017-04-30 16:46:09", description: nil},
  {name: "Sushipoint - Sushi Delivery Service!", link: "https://www.thuisbezorgd.nl/sushipoint-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12388, asset_updated_at: "2017-04-30 16:46:10", description: nil},
  {name: "Mooshka Vegan Food - Animal - Free Food", link: "https://www.thuisbezorgd.nl/mooshka", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 46298, asset_updated_at: "2017-04-30 16:46:10", description: nil},
  {name: "Sensu - Vietnamese en Japanse specialiteiten!", link: "https://www.thuisbezorgd.nl/sensu", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 36090, asset_updated_at: "2017-04-30 16:46:11", description: nil},
  {name: "Dapper Pizza - Gespecialiseerd in Döner en Pizza!", link: "https://www.thuisbezorgd.nl/dapper-pizza", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9177, asset_updated_at: "2017-04-30 16:46:11", description: nil},
  {name: "La Fermata Del Gusto - Ristorante Italiano Pizzeria", link: "https://www.thuisbezorgd.nl/la-fermata-del-gusto", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8405, asset_updated_at: "2017-04-30 16:46:12", description: nil},
  {name: "Frederique - Lekker en Gezond!", link: "https://www.thuisbezorgd.nl/frederique", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 14956, asset_updated_at: "2017-04-30 16:46:12", description: nil},
  {name: "Pizza Donna - Een van de beste pizzeria's van Amsterdam", link: "https://www.thuisbezorgd.nl/pizza-donna", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 71775, asset_updated_at: "2017-04-30 16:46:13", description: nil},
  {name: "Thai Food Cafe SOI Deli - De authentieke street food gerechten van Thailand", link: "https://www.thuisbezorgd.nl/thai-food-cafe-soi-74", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 3903, asset_updated_at: "2017-04-30 16:46:13", description: nil},
  {name: "Fresh Food Lovers - Food made with love for everyone", link: "https://www.thuisbezorgd.nl/fresh-food-lovers", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6532, asset_updated_at: "2017-04-30 16:46:14", description: nil},
  {name: "Pescara - Snel en lekker", link: "https://www.thuisbezorgd.nl/pescara", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4939, asset_updated_at: "2017-04-30 16:46:14", description: nil},
  {name: "Amantra Indian Cuisine - Indiaas Maaltijden", link: "https://www.thuisbezorgd.nl/amantra-indian-cuisine", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5743, asset_updated_at: "2017-04-30 16:46:15", description: nil},
  {name: "The Corner - Delicious Local Food & Drinks", link: "https://www.thuisbezorgd.nl/the-corner-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 38203, asset_updated_at: "2017-04-30 16:46:16", description: nil},
  {name: "Nefis Etliekmek - Nefis houtoven gerechten", link: "https://www.thuisbezorgd.nl/nefis-houtoven", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 24786, asset_updated_at: "2017-04-30 16:46:16", description: nil},
  {name: "Roopram - Grand Roopam Roti", link: "https://www.thuisbezorgd.nl/roopram", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 11612, asset_updated_at: "2017-04-30 16:46:17", description: nil},
  {name: "Sushi Profood - Moderne sushi", link: "https://www.thuisbezorgd.nl/sushi-profood", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6855, asset_updated_at: "2017-04-30 16:46:18", description: nil},
  {name: "Suvi - Sushi & Vietnamees Restaurant", link: "https://www.thuisbezorgd.nl/suvi", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5660, asset_updated_at: "2017-04-30 16:46:19", description: nil},
  {name: "Thai Food Cafe Soi 66 - de authentieke street food gerechten van Thailand", link: "https://www.thuisbezorgd.nl/thai-food-cafe", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 3903, asset_updated_at: "2017-04-30 16:46:19", description: nil},
  {name: "Pizzataxi da Paolo e Seba - Heerlijke Italiaanse Pizza's", link: "https://www.thuisbezorgd.nl/pizza-taxi", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12740, asset_updated_at: "2017-04-30 16:46:20", description: nil},
  {name: "Cigkoftem Dappermarkt - De lekkerste gerechten bestelt u hier!", link: "https://www.thuisbezorgd.nl/cigkoftem-dappermarkt-nieuw", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 15021, asset_updated_at: "2017-04-30 16:46:20", description: nil},
  {name: "Re Pizza - De eerste echte 'pizza al Tagglio', met liefde gemaakt", link: "https://www.thuisbezorgd.nl/re-pizza", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8238, asset_updated_at: "2017-04-30 16:46:21", description: nil},
  {name: "Komagene - Wraps, chee kofte en meer!", link: "https://www.thuisbezorgd.nl/komagene-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 15361, asset_updated_at: "2017-04-30 16:46:21", description: nil},
  {name: "Domino's Pizza - The Pizza Delivery Experts", link: "https://www.thuisbezorgd.nl/dominos-pizza-amsterdam-buitenveldert", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8026, asset_updated_at: "2017-04-30 16:46:22", description: nil},
  {name: "Indian Cuisine To Go - Tandoori, Curry, Vis, Kip, Lams &Vegetarische gerechten", link: "https://www.thuisbezorgd.nl/indian-cuisine-to-go-nieuw", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 18359, asset_updated_at: "2017-04-30 16:46:22", description: nil},
  {name: "Very Italian Place - Pizza, pasta en meer!", link: "https://www.thuisbezorgd.nl/very-italian-place", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 15001, asset_updated_at: "2017-04-30 16:46:23", description: nil},
  {name: "Liquor Store Late - Night - Drank tot in de late uurtjes!", link: "https://www.thuisbezorgd.nl/liquor-store", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12851, asset_updated_at: "2017-04-30 16:46:23", description: nil},
  {name: "Maydanoz - Mediterraanse Specialiteiten Restaurant", link: "https://www.thuisbezorgd.nl/maydanoz", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 17382, asset_updated_at: "2017-04-30 16:46:24", description: nil},
  {name: "Lunchroom Amalia - Amalia, breakfast, lunch and diner", link: "https://www.thuisbezorgd.nl/lunchroom-amalia", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 22605, asset_updated_at: "2017-04-30 16:46:24", description: nil},
  {name: "Patates - Ouderwets verse patat", link: "https://www.thuisbezorgd.nl/patates", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9663, asset_updated_at: "2017-04-30 16:46:25", description: nil},
  {name: "Mi Lobie - Surinaams / Chinees Eethuis - Sinds 1984", link: "https://www.thuisbezorgd.nl/mi-lobie", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4370, asset_updated_at: "2017-04-30 16:46:26", description: nil},
  {name: "Rijsttafel Express - Verfijnde delicatessen uit het Verre Oosten", link: "https://www.thuisbezorgd.nl/rijsttafel-express", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6972, asset_updated_at: "2017-04-30 16:46:26", description: nil},
  {name: "Eethuis Bocadillos - Heerlijk eten, goede prijs!", link: "https://www.thuisbezorgd.nl/eethuis-bocadillos-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6353, asset_updated_at: "2017-04-30 16:46:27", description: nil},
  {name: "Venkel Salades - Gemaakt met groenten van biologische boeren", link: "https://www.thuisbezorgd.nl/venkel", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4638, asset_updated_at: "2017-04-30 16:46:27", description: nil},
  {name: "Sushi n Sake - Fast and Fresh Food", link: "https://www.thuisbezorgd.nl/sushi-n-sake", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8668, asset_updated_at: "2017-04-30 16:46:28", description: nil},
  {name: "Napoli Pizza - Time for excellent pizza.", link: "https://www.thuisbezorgd.nl/napoli-pizza-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 14056, asset_updated_at: "2017-04-30 16:46:28", description: nil},
  {name: "Vijfnulvijf - ASIAN STREETBITES WITH AN URBAN VIBE", link: "https://www.thuisbezorgd.nl/vijfnulvijf", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10962, asset_updated_at: "2017-04-30 16:46:29", description: nil},
  {name: "Amerikaans Spareribs Line - Snelle bezorging en goede service", link: "https://www.thuisbezorgd.nl/amerikaans-spareribs-line", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4038, asset_updated_at: "2017-04-30 16:46:29", description: nil},
  {name: "Grill Wok - BBQ Grill, Traditional Wok.", link: "https://www.thuisbezorgd.nl/grill-wok-diemen-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 14568, asset_updated_at: "2017-04-30 16:46:30", description: nil},
  {name: "Zenzai Sushi - Exquisite taste at your doorstep!", link: "https://www.thuisbezorgd.nl/zenzai-sushi", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9385, asset_updated_at: "2017-04-30 16:46:30", description: nil},
  {name: "Nam Kee - Proef de beroemde Oesters van Nam Kee!", link: "https://www.thuisbezorgd.nl/nam-kee", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5037, asset_updated_at: "2017-04-30 16:46:31", description: nil},
  {name: "Bar Sue - Goed eten", link: "https://www.thuisbezorgd.nl/bar-sue", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7608, asset_updated_at: "2017-04-30 16:46:31", description: nil},
  {name: "Urfa Sofrasi - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/urfa-sofrasi-amsterdam-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 29363, asset_updated_at: "2017-04-30 16:46:32", description: nil},
  {name: "Pizzeria & Steakhouse Zeeburg - Smaakvol, Vers, Puur & Betaalbaar", link: "https://www.thuisbezorgd.nl/pizzeria-steakhouse-zeeburg", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 34144, asset_updated_at: "2017-04-30 16:46:33", description: nil},
  {name: "Takumi Burgers & Steaks - Smaakvolle burgers en steaks met Japanse twist!", link: "https://www.thuisbezorgd.nl/takumi-burgers-steaks", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19389, asset_updated_at: "2017-04-30 16:46:33", description: nil},
  {name: "Vle's Keuken - Echte Surinaamse keuken!", link: "https://www.thuisbezorgd.nl/vles-keuken", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9576, asset_updated_at: "2017-04-30 16:46:34", description: nil},
  {name: "Ela Palermo - Italiaans Restaurant Pizzeria", link: "https://www.thuisbezorgd.nl/ela-palermo", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9493, asset_updated_at: "2017-04-30 16:46:34", description: nil},
  {name: "Porto Pescara - Snel, warm en gratis thuisbezorgd", link: "https://www.thuisbezorgd.nl/porto-pescara", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4445, asset_updated_at: "2017-04-30 16:46:35", description: nil},
  {name: "Steakhouse Pizzeria Oost - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/steakhouse-pizzeria-oost", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 28928, asset_updated_at: "2017-04-30 16:46:36", description: nil},
  {name: "Pomorosso Ristorante Ceintuurbaan - Good Italian Food", link: "https://www.thuisbezorgd.nl/pomo-rosso", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 14459, asset_updated_at: "2017-04-30 16:46:36", description: nil},
  {name: "Pizzeria/Steakhouse La Roma - Restaurant, Pizzeria, Steakhouse", link: "https://www.thuisbezorgd.nl/pizzeriasteakhouse-la-roma", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6597, asset_updated_at: "2017-04-30 16:46:37", description: nil},
  {name: "Maccheroni - True, traditionally homemade cuisine", link: "https://www.thuisbezorgd.nl/maccheroni", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 15433, asset_updated_at: "2017-04-30 16:46:37", description: nil},
  {name: "Casa Pino 2 - De echte Italiaanse keuken en pizza's!", link: "https://www.thuisbezorgd.nl/casa-pino-2", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9419, asset_updated_at: "2017-04-30 16:46:38", description: nil},
  {name: "Restaurant Zirve - Turkish kitchen & pizzeria", link: "https://www.thuisbezorgd.nl/pasta-alforno", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7720, asset_updated_at: "2017-04-30 16:46:39", description: nil},
  {name: "Spare Rib Express - Your favourite meatpoint", link: "https://www.thuisbezorgd.nl/spare-rib-express-amsterdam-oost", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8474, asset_updated_at: "2017-04-30 16:46:39", description: nil},
  {name: "Madame Jeanette - Surinam Food & American Pastry", link: "https://www.thuisbezorgd.nl/madame-jeanette", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 15343, asset_updated_at: "2017-04-30 16:46:40", description: nil},
  {name: "Il Boccalino - Van klassieke pasta's tot malse vleesgerechten", link: "https://www.thuisbezorgd.nl/il-boccalino", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4650, asset_updated_at: "2017-04-30 16:46:40", description: nil},
  {name: "Sumo Take Away & Delivery - Sushi delivery!", link: "https://www.thuisbezorgd.nl/sumo-take-away-delivery-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 31165, asset_updated_at: "2017-04-30 16:46:41", description: nil},
  {name: "Bella Riva - Heerlijke  Italiaanse specialiteiten!", link: "https://www.thuisbezorgd.nl/bella-riva", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 28144, asset_updated_at: "2017-04-30 16:46:41", description: nil},
  {name: "Il Forno - Het gezellige restaurant!", link: "https://www.thuisbezorgd.nl/il-forno-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 29775, asset_updated_at: "2017-04-30 16:46:42", description: nil},
  {name: "Le Due Sicilie - Ristorante Pastificio Italiano", link: "https://www.thuisbezorgd.nl/le-due-sicilie", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 17813, asset_updated_at: "2017-04-30 16:46:42", description: nil},
  {name: "Naz Food & Snacks - Lekker eten bij Naz Food & Snacks!", link: "https://www.thuisbezorgd.nl/naz-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12351, asset_updated_at: "2017-04-30 16:46:43", description: nil},
  {name: "Agra Indian Express - Indian Cuisine", link: "https://www.thuisbezorgd.nl/agra-indian-express", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 14806, asset_updated_at: "2017-04-30 16:46:44", description: nil},
  {name: "Eethuis Tadim - 100% Halal", link: "https://www.thuisbezorgd.nl/eethuis-tadim", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 13388, asset_updated_at: "2017-04-30 16:46:44", description: nil},
  {name: "Indian & Indonesian Restaurant Vijaya - Het beste Indiaas eten in Amsterdam!", link: "https://www.thuisbezorgd.nl/vijaya-amsterdam-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 25379, asset_updated_at: "2017-04-30 16:46:45", description: nil},
  {name: "Sushi Kings - Fast fish!", link: "https://www.thuisbezorgd.nl/sushi-kings", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6943, asset_updated_at: "2017-04-30 16:46:45", description: nil},
  {name: "Sushi World - Take Away & Delivery", link: "https://www.thuisbezorgd.nl/sushi-world", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10400, asset_updated_at: "2017-04-30 16:46:46", description: nil},
  {name: "Daily Sushi - The best Sushi in town!", link: "https://www.thuisbezorgd.nl/daily-sushi", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7012, asset_updated_at: "2017-04-30 16:46:46", description: nil},
  {name: "MangiAccanto - Aperitivo, Pizzeria, Ristorante", link: "https://www.thuisbezorgd.nl/mangiamore", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 92615, asset_updated_at: "2017-04-30 16:46:47", description: nil},
  {name: "Tandoori Express - Indiaas & Surinaams bezorgcentrum. Halal!", link: "https://www.thuisbezorgd.nl/tandoori-express", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19249, asset_updated_at: "2017-04-30 16:46:48", description: nil},
  {name: "Roti Shop - Surinaams bezorgcentrum", link: "https://www.thuisbezorgd.nl/roti-shop", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 11028, asset_updated_at: "2017-04-30 16:46:48", description: nil},
  {name: "Wan Pipel - Surinaams - Indisch Restaurant - 100% Halal!", link: "https://www.thuisbezorgd.nl/wan-pipel", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5851, asset_updated_at: "2017-04-30 16:46:49", description: nil},
  {name: "Neetu Dhaba - Een topper in Amsterdam. Indiaas restaurant.", link: "https://www.thuisbezorgd.nl/neetu-dhaba", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5751, asset_updated_at: "2017-04-30 16:46:49", description: nil},
  {name: "Apna Tandoori - Lekker Indiaas", link: "https://www.thuisbezorgd.nl/apna-tandoori", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 11018, asset_updated_at: "2017-04-30 16:46:50", description: nil},
  {name: "Indian Kitchen - You've tried the rest - now try the best !", link: "https://www.thuisbezorgd.nl/indian-kitchen", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19721, asset_updated_at: "2017-04-30 16:46:51", description: nil},
  {name: "Curry Express - Indiaas & Surinaams Bezorgcentrum", link: "https://www.thuisbezorgd.nl/curry-express", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 21710, asset_updated_at: "2017-04-30 16:46:51", description: nil},
  {name: "Punjabi Dhaba Indian Food - Indiaas Restaurant", link: "https://www.thuisbezorgd.nl/punjabi-dhaba", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 11998, asset_updated_at: "2017-04-30 16:46:52", description: nil},
  {name: "Spuntino - De oudste pizzeria van Amsterdam!", link: "https://www.thuisbezorgd.nl/spuntino", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12760, asset_updated_at: "2017-04-30 16:46:52", description: nil},
  {name: "Warung Rahayu - Javaans Surinaams eethuis. Met trots 50 jaar kwaliteit!", link: "https://www.thuisbezorgd.nl/warung-rahayu", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 86252, asset_updated_at: "2017-04-30 16:46:53", description: nil},
  {name: "Valentino - Pizzeria", link: "https://www.thuisbezorgd.nl/pizza-presto", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 21242, asset_updated_at: "2017-04-30 16:46:54", description: nil},
  {name: "Roti Amsterdam - Roti en oosterse gerechten", link: "https://www.thuisbezorgd.nl/roti-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10189, asset_updated_at: "2017-04-30 16:46:54", description: nil},
  {name: "Rodos - Grieks en Italiaans", link: "https://www.thuisbezorgd.nl/rodos", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 33544, asset_updated_at: "2017-04-30 16:46:55", description: nil},
  {name: "Cigkoftem Vlugtlaan - De lekkerste gerechten bestelt u hier!", link: "https://www.thuisbezorgd.nl/cigkoftem-vlugtlaan", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 16813, asset_updated_at: "2017-04-30 16:46:55", description: nil},
  {name: "Orient Express - The best choice for delivery of Chinese meals!", link: "https://www.thuisbezorgd.nl/orient-express", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 3588, asset_updated_at: "2017-04-30 16:46:56", description: nil},
  {name: "Yummie Sushi & Pho - Vietnamees restaurant", link: "https://www.thuisbezorgd.nl/pho-house", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10258, asset_updated_at: "2017-04-30 16:46:56", description: nil},
  {name: "Chopstix - Asian Modern Fusion", link: "https://www.thuisbezorgd.nl/chopstix", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5378, asset_updated_at: "2017-04-30 16:46:57", description: nil},
  {name: "Haweli Indian Food - World Famous Indian Restaurant", link: "https://www.thuisbezorgd.nl/haweli-indian-food", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10040, asset_updated_at: "2017-04-30 16:46:57", description: nil},
  {name: "Aarti 2 - Het lekkerste Surinaamse eten!", link: "https://www.thuisbezorgd.nl/aarti-2", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12430, asset_updated_at: "2017-04-30 16:46:58", description: nil},
  {name: "Toko Gein - 100% Halal", link: "https://www.thuisbezorgd.nl/toko-gein", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9029, asset_updated_at: "2017-04-30 16:46:59", description: nil},
  {name: "Sushi Sakura - Elke dag verse vis!", link: "https://www.thuisbezorgd.nl/sushi-sakura", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 32739, asset_updated_at: "2017-04-30 16:46:59", description: nil},
  {name: "H/EART.H - Vegetarisch", link: "https://www.thuisbezorgd.nl/hearth", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5114, asset_updated_at: "2017-04-30 16:47:00", description: nil},
  {name: "Pasta Vino - De échte Italiaan op het Java-Eiland", link: "https://www.thuisbezorgd.nl/pasta-vino", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 18892, asset_updated_at: "2017-04-30 16:47:00", description: nil},
  {name: "Palace of India - Indiaas traditional food", link: "https://www.thuisbezorgd.nl/palace-of-india", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5791, asset_updated_at: "2017-04-30 16:47:01", description: nil},
  {name: "Mt. Everest - MT EVEREST Nepalese en Indiaas", link: "https://www.thuisbezorgd.nl/mt-everest", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9944, asset_updated_at: "2017-04-30 16:47:01", description: nil},
  {name: "Cigkoftem Mercator - De lekkerste gerechten bestelt u hier!", link: "https://www.thuisbezorgd.nl/cigkoftem-west", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 16813, asset_updated_at: "2017-04-30 16:47:02", description: nil},
  {name: "Indian Food Express - Traditionele Indiase Gerechten", link: "https://www.thuisbezorgd.nl/indian-food-express-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10011, asset_updated_at: "2017-04-30 16:47:02", description: nil},
  {name: "Thai Kitchen - The only one! (100% halal)", link: "https://www.thuisbezorgd.nl/thai-kitchen-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19442, asset_updated_at: "2017-04-30 16:47:03", description: nil},
  {name: "Desi Tarka - Lekkerste roti, nasi, bami, curry's & tandoori", link: "https://www.thuisbezorgd.nl/desi-tarka", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12230, asset_updated_at: "2017-04-30 16:47:03", description: nil},
  {name: "Pizza-Meester - De beste pizza's van Amsterdam!", link: "https://www.thuisbezorgd.nl/pizza-meester", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7546, asset_updated_at: "2017-04-30 16:47:04", description: nil},
  {name: "Desi Tawa - Tasty Indian Food! 100% halal!!!", link: "https://www.thuisbezorgd.nl/desi-tawa", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19093, asset_updated_at: "2017-04-30 16:47:04", description: nil},
  {name: "Il Delfino Blu - Authentieke Italiaanse gerechten", link: "https://www.thuisbezorgd.nl/il-delfino-blu", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 65308, asset_updated_at: "2017-04-30 16:47:05", description: nil},
  {name: "African Kitchen - Authentiek Afrikaans", link: "https://www.thuisbezorgd.nl/african-kitchen", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12765, asset_updated_at: "2017-04-30 16:47:06", description: nil},
  {name: "24/7 Burgerhouse - Heerlijke burgers, wraps en snacks!", link: "https://www.thuisbezorgd.nl/247-burgerhouse", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 43264, asset_updated_at: "2017-04-30 16:47:06", description: nil},
  {name: "Any Thaim Delivery - Nieuw in Amsterdam Noord: Authentiek afhaal/bezorg Thai", link: "https://www.thuisbezorgd.nl/any-thaim-delivery", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10538, asset_updated_at: "2017-04-30 16:47:07", description: nil},
  {name: "Valentino's food@night - Snacks - Panini's - Broodjes", link: "https://www.thuisbezorgd.nl/valentinos-foodnight", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8610, asset_updated_at: "2017-04-30 16:47:07", description: nil},
  {name: "24/7 Pizza - Great pizza's with fresh ingredients", link: "https://www.thuisbezorgd.nl/247-pizza", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 14108, asset_updated_at: "2017-04-30 16:47:08", description: nil},
  {name: "Eat at Night - Eat at night when you're hungry at night", link: "https://www.thuisbezorgd.nl/eatnight", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 45493, asset_updated_at: "2017-04-30 16:47:08", description: nil},
  {name: "Drink2Night - Snel geleverd!", link: "https://www.thuisbezorgd.nl/drink2night", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5366, asset_updated_at: "2017-04-30 16:47:09", description: nil},
  {name: "247DRANK - Place your order with 247DRANK.", link: "https://www.thuisbezorgd.nl/247drank", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7740, asset_updated_at: "2017-04-30 16:47:09", description: nil},
  {name: "Bierbezorgd - Bierbezorgd levert bier en méér buiten winkeltijden!", link: "https://www.thuisbezorgd.nl/bierbezorgd", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 27693, asset_updated_at: "2017-04-30 16:47:10", description: nil},
  {name: "Day and Night Pizza - All day, All night!", link: "https://www.thuisbezorgd.nl/day-and-night-pizza", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 22025, asset_updated_at: "2017-04-30 16:47:11", description: nil},
  {name: "Pizza aan het IJ - 24h midnight express!", link: "https://www.thuisbezorgd.nl/pizza-aan-het-ij", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 50002, asset_updated_at: "2017-04-30 16:47:11", description: nil},
  {name: "Anytime Pizza 24h - De heerlijkste gerechten tot diep in de nacht bezorgd!", link: "https://www.thuisbezorgd.nl/anytime-pizza24h", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6572, asset_updated_at: "2017-04-30 16:47:12", description: nil},
  {name: "Nightshop Amsterdam - Wij bezorgen zonder zorgen!", link: "https://www.thuisbezorgd.nl/nightshop", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 13736, asset_updated_at: "2017-04-30 16:47:12", description: nil},
  {name: "Gusto Di Casto - Proef de echte Italiaanse smaak", link: "https://www.thuisbezorgd.nl/gusto-di-casto", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10473, asset_updated_at: "2017-04-30 16:47:13", description: nil},
  {name: "Sifu Sifu - Echt authentiek Chinees", link: "https://www.thuisbezorgd.nl/sifusifu", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 11712, asset_updated_at: "2017-04-30 16:47:14", description: nil},
  {name: "Eetlicht - Bezorging en Catering!", link: "https://www.thuisbezorgd.nl/eetlicht-2", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19021, asset_updated_at: "2017-04-30 16:47:14", description: nil},
  {name: "Eatalia Gastronomia - Authentiek Italiaans", link: "https://www.thuisbezorgd.nl/eatalia-gastronomia", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 42151, asset_updated_at: "2017-04-30 16:47:15", description: nil},
  {name: "Sandwich Express - Altijd vers en op de afgesproken tijd!", link: "https://www.thuisbezorgd.nl/sandwich-express", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 42896, asset_updated_at: "2017-04-30 16:47:15", description: nil},
  {name: "Baan Pong Thais Eethuis - Orginele Thaise maaltijden", link: "https://www.thuisbezorgd.nl/baan-pong-thais-eethuis", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8326, asset_updated_at: "2017-04-30 16:47:16", description: nil},
  {name: "De Bicker - Overheerlijke Spare Ribs", link: "https://www.thuisbezorgd.nl/de-bicker-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 94932, asset_updated_at: "2017-04-30 16:47:17", description: nil},
  {name: "A-Markt - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/a-markt", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5585, asset_updated_at: "2017-04-30 16:47:17", description: nil},
  {name: "Foodies Traiteur - Alles is vers en ter plekke bereid", link: "https://www.thuisbezorgd.nl/foodies-traiteur", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6283, asset_updated_at: "2017-04-30 16:47:18", description: nil},
  {name: "AK Hicret - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/ak-hicret", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6756, asset_updated_at: "2017-04-30 16:47:18", description: nil},
  {name: "Tjin's exotische broodjes - De oudste Surinaamse broodjeszaak van Nederland!", link: "https://www.thuisbezorgd.nl/tjins-exotische-broodjes", chosen: true, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7459, asset_updated_at: "2017-04-30 16:47:19", description: ""},
  {name: "Johnny's Burger Company - Burgers and more!", link: "https://www.thuisbezorgd.nl/johnnys-burger-company-ceintuurbaan", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9453, asset_updated_at: "2017-04-30 16:47:19", description: nil},
  {name: "Wokhuis Amsterdam - Ervaar nu de VERNIEUWDE en SMAAKVOLLE wokgerechten!", link: "https://www.thuisbezorgd.nl/wokhuis-amsterdam-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 33283, asset_updated_at: "2017-04-30 16:47:20", description: nil},
  {name: "Elegance Ahlem Café Restaurant - Goed eten, goede prijs!", link: "https://www.thuisbezorgd.nl/cafe-restaurant-han", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10574, asset_updated_at: "2017-04-30 16:47:20", description: nil},
  {name: "Carmen's Food Corner - Surinaams/Chinees Eethuis!", link: "https://www.thuisbezorgd.nl/carmens-food-corner", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 53754, asset_updated_at: "2017-04-30 16:47:21", description: nil},
  {name: "Domino's Pizza - The Pizza delivery experts", link: "https://www.thuisbezorgd.nl/dominos-pizza-amsterdam-buitenveldert-lunch", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 8026, asset_updated_at: "2017-04-30 16:47:22", description: nil},
  {name: "Broodjeszaak de Valentino 2 - Snacks - Panini's - Broodjes", link: "https://www.thuisbezorgd.nl/broodjeszaak-de-valentino-2", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 19881, asset_updated_at: "2017-04-30 16:47:22", description: nil},
  {name: "Keurslagerij van Vliet - Hollands eten zoals het hoort!", link: "https://www.thuisbezorgd.nl/meneer-van-dalen", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4650, asset_updated_at: "2017-04-30 16:47:23", description: nil},
  {name: "Steakhouse Jaffa - Steakhouse & Fried Chicken!", link: "https://www.thuisbezorgd.nl/steakhouse-jaffa", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 6025, asset_updated_at: "2017-04-30 16:47:23", description: nil},
  {name: "Vishandel Albert Cuyp - Seafood with a twist", link: "https://www.thuisbezorgd.nl/vishandel-albert-cuyp", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 102522, asset_updated_at: "2017-04-30 16:47:24", description: nil},
  {name: "Pompoen met Speck - Eerlijk en bewust eten met het seizoen mee", link: "https://www.thuisbezorgd.nl/pompoen-met-speck", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 11365, asset_updated_at: "2017-04-30 16:47:24", description: nil},
  {name: "Broodje Popov - Popov's sandwiches & drinks to go", link: "https://www.thuisbezorgd.nl/broodje-popov", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 17208, asset_updated_at: "2017-04-30 16:47:25", description: nil},
  {name: "King Doner - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/king-doner-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 14357, asset_updated_at: "2017-04-30 16:47:26", description: nil},
  {name: "Mimi - écht Italiaans eten", link: "https://www.thuisbezorgd.nl/mimi-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 7773, asset_updated_at: "2017-04-30 16:47:26", description: nil},
  {name: "Santorini Greek Taverna - Heerlijk eten!", link: "https://www.thuisbezorgd.nl/santorini-greek-taverna", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 5481, asset_updated_at: "2017-04-30 16:47:27", description: nil},
  {name: "Bierisop - Gegarandeerd koud bezorgd!", link: "https://www.thuisbezorgd.nl/bierisop", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 37328, asset_updated_at: "2017-04-30 16:47:27", description: nil},
  {name: "Duncan's Place - Steak, Vis, Kip, Wok...", link: "https://www.thuisbezorgd.nl/duncans-place", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10501, asset_updated_at: "2017-04-30 16:47:28", description: nil},
  {name: "Sandwich & Grill - Sandwich & Grill", link: "https://www.thuisbezorgd.nl/sandwich-grill", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 12778, asset_updated_at: "2017-04-30 16:47:29", description: nil},
  {name: "Thailicious - Straight Outta Bangkok!", link: "https://www.thuisbezorgd.nl/thailicious-living", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 10741, asset_updated_at: "2017-04-30 16:47:30", description: nil},
  {name: "Club Koffie - Heerlijke Clubsandwiches", link: "https://www.thuisbezorgd.nl/club-koffie", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 2931, asset_updated_at: "2017-04-30 16:47:30", description: nil},
  {name: "Science Döner - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/fuamuh", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4609, asset_updated_at: "2017-04-30 16:47:31", description: nil},
  {name: "BobbysBurgers - Delicious fresh tasty Burgers", link: "https://www.thuisbezorgd.nl/bobbysburgers-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 151934, asset_updated_at: "2017-04-30 16:47:31", description: nil},
  {name: "Bellissima - Lekkere broodjes, panini's en salades van Bellissima!", link: "https://www.thuisbezorgd.nl/bellissima-amsterdam", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 4668, asset_updated_at: "2017-04-30 16:47:32", description: nil},
  {name: "Tajine Express - Lekker eten, goede prijs!", link: "https://www.thuisbezorgd.nl/tajine-express", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 16542, asset_updated_at: "2017-04-30 16:47:32", description: nil},
  {name: "BRIES - Coffee Food Drinks", link: "https://www.thuisbezorgd.nl/bries", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 9896, asset_updated_at: "2017-04-30 16:47:33", description: nil},
  {name: "De Korte Prins - Bedrijfscatering", link: "https://www.thuisbezorgd.nl/de-korte-prins", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 47373, asset_updated_at: "2017-04-30 16:47:33", description: nil},
  {name: "Chicken Palace - The best grilled and fried chicken! 100% halal!", link: "https://www.thuisbezorgd.nl/chicken-palace-amsterdam-1", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 15525, asset_updated_at: "2017-04-30 16:47:34", description: nil},
  {name: "Gallizia Deli - Cafe, Focaccia, Vino", link: "https://www.thuisbezorgd.nl/gallizia-deli", chosen: false, asset_file_name: "logo_465x320.png", asset_content_type: "image/png", asset_file_size: 52594, asset_updated_at: "2017-04-30 16:47:35", description: nil},
  {name: "litedark urbanfood", link: "https://www.thuisbezorgd.nl/litedark-1", chosen: true, asset_file_name: "litedark.png", asset_content_type: "image/png", asset_file_size: 95488, asset_updated_at: "2017-04-30 16:53:18", description: "Was Really Good"},
  {name: "Saigon Caphe Gelderlandplein", link: "https://www.thuisbezorgd.nl/saigon-caphe-1", chosen: true, asset_file_name: "food-category.png", asset_content_type: "image/png", asset_file_size: 180809, asset_updated_at: "2017-04-30 17:48:27", description: "Was Really Good"}
])
Restaurant::Translation.create!([
  {restaurant_id: 1, locale: "en", description: nil},
  {restaurant_id: 2, locale: "en", description: nil},
  {restaurant_id: 3, locale: "en", description: nil},
  {restaurant_id: 4, locale: "en", description: nil},
  {restaurant_id: 5, locale: "en", description: nil},
  {restaurant_id: 6, locale: "en", description: nil},
  {restaurant_id: 7, locale: "en", description: nil},
  {restaurant_id: 8, locale: "en", description: nil},
  {restaurant_id: 9, locale: "en", description: nil},
  {restaurant_id: 10, locale: "en", description: nil},
  {restaurant_id: 11, locale: "en", description: nil},
  {restaurant_id: 12, locale: "en", description: nil},
  {restaurant_id: 13, locale: "en", description: nil},
  {restaurant_id: 14, locale: "en", description: nil},
  {restaurant_id: 15, locale: "en", description: nil},
  {restaurant_id: 16, locale: "en", description: nil},
  {restaurant_id: 17, locale: "en", description: nil},
  {restaurant_id: 18, locale: "en", description: nil},
  {restaurant_id: 19, locale: "en", description: nil},
  {restaurant_id: 20, locale: "en", description: nil},
  {restaurant_id: 21, locale: "en", description: nil},
  {restaurant_id: 22, locale: "en", description: nil},
  {restaurant_id: 23, locale: "en", description: nil},
  {restaurant_id: 24, locale: "en", description: nil},
  {restaurant_id: 25, locale: "en", description: nil},
  {restaurant_id: 26, locale: "en", description: nil},
  {restaurant_id: 27, locale: "en", description: nil},
  {restaurant_id: 28, locale: "en", description: nil},
  {restaurant_id: 29, locale: "en", description: nil},
  {restaurant_id: 30, locale: "en", description: nil},
  {restaurant_id: 31, locale: "en", description: nil},
  {restaurant_id: 32, locale: "en", description: nil},
  {restaurant_id: 33, locale: "en", description: nil},
  {restaurant_id: 34, locale: "en", description: nil},
  {restaurant_id: 35, locale: "en", description: nil},
  {restaurant_id: 36, locale: "en", description: nil},
  {restaurant_id: 37, locale: "en", description: nil},
  {restaurant_id: 38, locale: "en", description: nil},
  {restaurant_id: 39, locale: "en", description: nil},
  {restaurant_id: 40, locale: "en", description: nil},
  {restaurant_id: 41, locale: "en", description: nil},
  {restaurant_id: 42, locale: "en", description: nil},
  {restaurant_id: 43, locale: "en", description: nil},
  {restaurant_id: 44, locale: "en", description: nil},
  {restaurant_id: 45, locale: "en", description: nil},
  {restaurant_id: 46, locale: "en", description: nil},
  {restaurant_id: 47, locale: "en", description: nil},
  {restaurant_id: 48, locale: "en", description: nil},
  {restaurant_id: 49, locale: "en", description: nil},
  {restaurant_id: 50, locale: "en", description: nil},
  {restaurant_id: 51, locale: "en", description: nil},
  {restaurant_id: 52, locale: "en", description: nil},
  {restaurant_id: 53, locale: "en", description: nil},
  {restaurant_id: 54, locale: "en", description: nil},
  {restaurant_id: 55, locale: "en", description: nil},
  {restaurant_id: 56, locale: "en", description: nil},
  {restaurant_id: 57, locale: "en", description: nil},
  {restaurant_id: 58, locale: "en", description: nil},
  {restaurant_id: 59, locale: "en", description: nil},
  {restaurant_id: 60, locale: "en", description: nil},
  {restaurant_id: 61, locale: "en", description: nil},
  {restaurant_id: 62, locale: "en", description: nil},
  {restaurant_id: 63, locale: "en", description: nil},
  {restaurant_id: 64, locale: "en", description: nil},
  {restaurant_id: 65, locale: "en", description: nil},
  {restaurant_id: 66, locale: "en", description: nil},
  {restaurant_id: 67, locale: "en", description: nil},
  {restaurant_id: 68, locale: "en", description: nil},
  {restaurant_id: 69, locale: "en", description: nil},
  {restaurant_id: 70, locale: "en", description: nil},
  {restaurant_id: 71, locale: "en", description: nil},
  {restaurant_id: 72, locale: "en", description: nil},
  {restaurant_id: 73, locale: "en", description: nil},
  {restaurant_id: 74, locale: "en", description: nil},
  {restaurant_id: 75, locale: "en", description: nil},
  {restaurant_id: 76, locale: "en", description: nil},
  {restaurant_id: 77, locale: "en", description: nil},
  {restaurant_id: 78, locale: "en", description: nil},
  {restaurant_id: 79, locale: "en", description: nil},
  {restaurant_id: 80, locale: "en", description: nil},
  {restaurant_id: 81, locale: "en", description: nil},
  {restaurant_id: 82, locale: "en", description: nil},
  {restaurant_id: 83, locale: "en", description: nil},
  {restaurant_id: 84, locale: "en", description: nil},
  {restaurant_id: 85, locale: "en", description: nil},
  {restaurant_id: 86, locale: "en", description: nil},
  {restaurant_id: 87, locale: "en", description: nil},
  {restaurant_id: 88, locale: "en", description: nil},
  {restaurant_id: 89, locale: "en", description: nil},
  {restaurant_id: 90, locale: "en", description: nil},
  {restaurant_id: 91, locale: "en", description: nil},
  {restaurant_id: 92, locale: "en", description: nil},
  {restaurant_id: 93, locale: "en", description: nil},
  {restaurant_id: 94, locale: "en", description: nil},
  {restaurant_id: 95, locale: "en", description: nil},
  {restaurant_id: 96, locale: "en", description: nil},
  {restaurant_id: 97, locale: "en", description: nil},
  {restaurant_id: 98, locale: "en", description: nil},
  {restaurant_id: 99, locale: "en", description: nil},
  {restaurant_id: 100, locale: "en", description: nil},
  {restaurant_id: 101, locale: "en", description: nil},
  {restaurant_id: 102, locale: "en", description: nil},
  {restaurant_id: 103, locale: "en", description: nil},
  {restaurant_id: 104, locale: "en", description: nil},
  {restaurant_id: 105, locale: "en", description: nil},
  {restaurant_id: 106, locale: "en", description: nil},
  {restaurant_id: 107, locale: "en", description: nil},
  {restaurant_id: 108, locale: "en", description: nil},
  {restaurant_id: 109, locale: "en", description: nil},
  {restaurant_id: 110, locale: "en", description: nil},
  {restaurant_id: 111, locale: "en", description: nil},
  {restaurant_id: 112, locale: "en", description: nil},
  {restaurant_id: 113, locale: "en", description: nil},
  {restaurant_id: 114, locale: "en", description: nil},
  {restaurant_id: 115, locale: "en", description: nil},
  {restaurant_id: 116, locale: "en", description: nil},
  {restaurant_id: 117, locale: "en", description: nil},
  {restaurant_id: 118, locale: "en", description: nil},
  {restaurant_id: 119, locale: "en", description: nil},
  {restaurant_id: 120, locale: "en", description: nil},
  {restaurant_id: 121, locale: "en", description: nil},
  {restaurant_id: 122, locale: "en", description: nil},
  {restaurant_id: 123, locale: "en", description: nil},
  {restaurant_id: 124, locale: "en", description: nil},
  {restaurant_id: 125, locale: "en", description: nil},
  {restaurant_id: 126, locale: "en", description: nil},
  {restaurant_id: 127, locale: "en", description: nil},
  {restaurant_id: 128, locale: "en", description: nil},
  {restaurant_id: 129, locale: "en", description: nil},
  {restaurant_id: 130, locale: "en", description: nil},
  {restaurant_id: 131, locale: "en", description: nil},
  {restaurant_id: 132, locale: "en", description: nil},
  {restaurant_id: 133, locale: "en", description: nil},
  {restaurant_id: 134, locale: "en", description: nil},
  {restaurant_id: 135, locale: "en", description: nil},
  {restaurant_id: 136, locale: "en", description: nil},
  {restaurant_id: 137, locale: "en", description: nil},
  {restaurant_id: 138, locale: "en", description: nil},
  {restaurant_id: 139, locale: "en", description: nil},
  {restaurant_id: 140, locale: "en", description: nil},
  {restaurant_id: 141, locale: "en", description: nil},
  {restaurant_id: 142, locale: "en", description: nil},
  {restaurant_id: 143, locale: "en", description: nil},
  {restaurant_id: 144, locale: "en", description: nil},
  {restaurant_id: 145, locale: "en", description: nil},
  {restaurant_id: 146, locale: "en", description: nil},
  {restaurant_id: 147, locale: "en", description: nil},
  {restaurant_id: 148, locale: "en", description: nil},
  {restaurant_id: 149, locale: "en", description: nil},
  {restaurant_id: 150, locale: "en", description: nil},
  {restaurant_id: 151, locale: "en", description: nil},
  {restaurant_id: 152, locale: "en", description: nil},
  {restaurant_id: 153, locale: "en", description: nil},
  {restaurant_id: 154, locale: "en", description: nil},
  {restaurant_id: 155, locale: "en", description: nil},
  {restaurant_id: 156, locale: "en", description: nil},
  {restaurant_id: 157, locale: "en", description: nil},
  {restaurant_id: 158, locale: "en", description: nil},
  {restaurant_id: 159, locale: "en", description: nil},
  {restaurant_id: 160, locale: "en", description: nil},
  {restaurant_id: 161, locale: "en", description: nil},
  {restaurant_id: 162, locale: "en", description: nil},
  {restaurant_id: 163, locale: "en", description: nil},
  {restaurant_id: 164, locale: "en", description: nil},
  {restaurant_id: 165, locale: "en", description: nil},
  {restaurant_id: 166, locale: "en", description: nil},
  {restaurant_id: 167, locale: "en", description: nil},
  {restaurant_id: 168, locale: "en", description: ""},
  {restaurant_id: 169, locale: "en", description: nil},
  {restaurant_id: 170, locale: "en", description: nil},
  {restaurant_id: 171, locale: "en", description: nil},
  {restaurant_id: 172, locale: "en", description: nil},
  {restaurant_id: 173, locale: "en", description: nil},
  {restaurant_id: 174, locale: "en", description: nil},
  {restaurant_id: 175, locale: "en", description: nil},
  {restaurant_id: 176, locale: "en", description: nil},
  {restaurant_id: 177, locale: "en", description: nil},
  {restaurant_id: 178, locale: "en", description: nil},
  {restaurant_id: 179, locale: "en", description: nil},
  {restaurant_id: 180, locale: "en", description: nil},
  {restaurant_id: 181, locale: "en", description: nil},
  {restaurant_id: 182, locale: "en", description: nil},
  {restaurant_id: 183, locale: "en", description: nil},
  {restaurant_id: 184, locale: "en", description: nil},
  {restaurant_id: 185, locale: "en", description: nil},
  {restaurant_id: 186, locale: "en", description: nil},
  {restaurant_id: 187, locale: "en", description: nil},
  {restaurant_id: 188, locale: "en", description: nil},
  {restaurant_id: 189, locale: "en", description: nil},
  {restaurant_id: 190, locale: "en", description: nil},
  {restaurant_id: 191, locale: "en", description: nil},
  {restaurant_id: 192, locale: "en", description: nil},
  {restaurant_id: 193, locale: "en", description: nil},
  {restaurant_id: 194, locale: "en", description: nil},
  {restaurant_id: 195, locale: "en", description: nil},
  {restaurant_id: 196, locale: "en", description: "Was Really Good"},
  {restaurant_id: 196, locale: "pt-BR", description: "Era muito Bom!"},
  {restaurant_id: 197, locale: "pt-BR", description: "Era muito Bom!!!!"},
  {restaurant_id: 197, locale: "en", description: "Was Really Good"}
])
